/**
 * Client-side PDF for live medical translation sessions (jsPDF).
 * No server upload; no transcript logging.
 */
import { jsPDF } from "jspdf";
import { getMessages } from "../../../i18n/translations/index.js";
import { getPrimaryIntlLocale } from "../../../i18n/intlLocale.js";
import { liveTranslationLanguageLabel } from "../languages.js";

const COL = {
  slate: [15, 23, 42],
  slateMuted: [71, 85, 105],
  teal: [14, 116, 144],
  rule: [226, 232, 240],
  boxBg: [248, 250, 252],
  boxBorder: [203, 213, 225],
  safetyBg: [255, 251, 235],
  safetyBorder: [253, 230, 138],
};

const FOOTER_RESERVE_MM = 24;

function sanitizePdfText(v) {
  return String(v ?? "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .trimEnd();
}

function lineHeightMm(fontSizePt) {
  return fontSizePt * 0.352778 * 1.35;
}

function defaultPdfLabels(uiLanguage) {
  const M = getMessages(uiLanguage);
  const pdf = M.liveMedicalTranslation?.pdf;
  if (pdf && typeof pdf === "object" && pdf.documentTitle) {
    return pdf;
  }
  const de = String(uiLanguage || "").toLowerCase().startsWith("de");
  return de
    ? {
        documentTitle: "Übersetztes Gesprächsprotokoll",
        safetyNotice:
          "Dieses Dokument dient der Kommunikation und Übersetzung. Es ist keine Diagnose, keine Triage und keine Behandlungsempfehlung. Automatische Transkriptionen und Übersetzungen können Fehler enthalten und sollten bei wichtigen Angaben überprüft werden.",
        sectionPatient: "Patient",
        sectionPractice: "Praxis / Arzt",
        sectionSession: "Sitzung",
        sectionConversation: "Gesprächsprotokoll",
        patientName: "Name",
        birthDate: "Geburtsdatum",
        patientLanguage: "Patientensprache",
        doctorLanguage: "Arzt-/Praxissprache",
        practiceName: "Praxisname",
        doctorName: "Arztname",
        specialty: "Fachrichtung",
        practiceAddress: "Adresse",
        insurance: "Krankenkasse",
        appointmentNote: "Terminnotiz / Anlass",
        sessionStart: "Beginn",
        sessionEnd: "Ende",
        languagePair: "Sprachenpaar",
        autoSwitch: "Automatischer Sprecherwechsel",
        notProvided: "Nicht angegeben",
        yes: "Ja",
        no: "Nein",
        speakerPatient: "Patient",
        speakerDoctor: "Arzt/Praxis",
        originalLabel: "Original",
        translationLabel: "Übersetzung",
        originalMissing: "Original nicht sicher erkannt",
        statusTranslated: "Übersetzt",
        statusUnclear: "Unklar",
        statusCorrected: "Korrigiert",
        statusReplayed: "Erneut vorgelesen",
        wrongVersion: "Ursprüngliche Version",
        correctedVersion: "Korrigierte Version",
        footerGenerated: "Erstellt von MedScoutX · Nur Kommunikationsprotokoll",
        footerPage: "Seite",
        filename: "medscoutx-gespraechsprotokoll.pdf",
      }
    : {
        documentTitle: "Translated conversation record",
        safetyNotice:
          "This document supports communication and translation only. It is not a diagnosis, triage, or treatment recommendation. Automatic transcription and translation may contain errors and should be verified for important information.",
        sectionPatient: "Patient",
        sectionPractice: "Practice / doctor",
        sectionSession: "Session",
        sectionConversation: "Conversation record",
        patientName: "Name",
        birthDate: "Date of birth",
        patientLanguage: "Patient language",
        doctorLanguage: "Doctor/practice language",
        practiceName: "Practice name",
        doctorName: "Doctor name",
        specialty: "Specialty",
        practiceAddress: "Address",
        insurance: "Health insurance",
        appointmentNote: "Appointment note / reason",
        sessionStart: "Start",
        sessionEnd: "End",
        languagePair: "Language pair",
        autoSwitch: "Automatic speaker switch",
        notProvided: "Not provided",
        yes: "Yes",
        no: "No",
        speakerPatient: "Patient",
        speakerDoctor: "Doctor/practice",
        originalLabel: "Original",
        translationLabel: "Translation",
        originalMissing: "Original not reliably recognized",
        statusTranslated: "Translated",
        statusUnclear: "Unclear",
        statusCorrected: "Corrected",
        statusReplayed: "Replayed",
        wrongVersion: "Original version",
        correctedVersion: "Corrected version",
        footerGenerated: "Generated by MedScoutX · Communication record only",
        footerPage: "Page",
        filename: "medscoutx-conversation-record.pdf",
      };
}

function formatDateTime(iso, uiLanguage) {
  try {
    return new Date(iso).toLocaleString(getPrimaryIntlLocale(uiLanguage), {
      dateStyle: "medium",
      timeStyle: "short",
    });
  } catch {
    return iso;
  }
}

function formatBirthDate(isoDate, uiLanguage) {
  try {
    const [y, m, d] = isoDate.split("-").map(Number);
    if (!y || !m || !d) return isoDate;
    return new Date(y, m - 1, d).toLocaleDateString(getPrimaryIntlLocale(uiLanguage), {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    });
  } catch {
    return isoDate;
  }
}

function statusLabel(L, status) {
  switch (status) {
    case "unclear":
      return L.statusUnclear;
    case "corrected":
      return L.statusCorrected;
    case "replayed":
      return L.statusReplayed;
    default:
      return L.statusTranslated;
  }
}

function applyFooters(doc, L, pageWidth, pageHeight, margin, generatedAt) {
  const total = doc.internal.getNumberOfPages();
  const lh = lineHeightMm(7.5);

  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    const noteY = pageHeight - margin - 2;
    const brandY = noteY - lh - 2;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...COL.slateMuted);
    doc.text("MedScoutX", margin, brandY);
    doc.text(`${L.footerPage} ${p} / ${total}`, pageWidth - margin, brandY, { align: "right" });
    doc.text(`${L.footerGenerated} · ${generatedAt}`, margin, noteY);
    doc.setTextColor(...COL.slate);
  }
}

/**
 * @param {ReturnType<typeof import("../utils/sessionMetadata.js").buildExportMetadata>} exportData
 * @param {string} uiLanguage
 */
export function buildLiveTranslationPdfDocument(exportData, uiLanguage) {
  if (!exportData) return null;

  const L = defaultPdfLabels(uiLanguage);
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageWidth - 2 * margin;
  let y = margin;

  const bodySize = 10;
  const labelSize = 9.5;
  const sectionSize = 12;
  const titleSize = 16;
  const brandSize = 11;

  const generatedAt = formatDateTime(exportData.sessionEndedAt || new Date().toISOString(), uiLanguage);
  const contentBottomY = () => pageHeight - margin - FOOTER_RESERVE_MM;

  function needSpace(mm) {
    if (y + mm > contentBottomY()) {
      doc.addPage();
      y = margin;
    }
  }

  function gap(mm) {
    y += mm;
  }

  function drawWrapped(raw, width, fontSizePt, opts = {}) {
    const text = sanitizePdfText(raw);
    const lh = lineHeightMm(fontSizePt);
    const lines = doc.splitTextToSize(text, width);
    for (const line of lines) {
      needSpace(lh + 0.5);
      doc.text(line, margin, y, { align: opts.align || "left" });
      y += lh;
    }
  }

  function drawSectionTitle(title) {
    gap(4);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(sectionSize);
    doc.setTextColor(...COL.teal);
    drawWrapped(title, contentW, sectionSize);
    doc.setTextColor(...COL.slate);
    gap(2);
    doc.setDrawColor(...COL.rule);
    doc.setLineWidth(0.35);
    doc.line(margin, y, pageWidth - margin, y);
    gap(5);
  }

  function drawMetaRow(label, value) {
    const val = String(value || "").trim();
    if (!val) return;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(labelSize);
    drawWrapped(`${label}:`, contentW, labelSize);
    gap(1);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(bodySize);
    drawWrapped(val, contentW, bodySize);
    gap(4);
  }

  // Header
  doc.setTextColor(...COL.teal);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(brandSize);
  needSpace(lineHeightMm(brandSize));
  doc.text("MedScoutX", margin, y);
  y += lineHeightMm(brandSize) + 2;

  doc.setTextColor(...COL.slate);
  doc.setFontSize(titleSize);
  drawWrapped(L.documentTitle, contentW, titleSize);
  gap(2);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(bodySize);
  doc.setTextColor(...COL.slateMuted);
  drawWrapped(generatedAt, contentW, bodySize);
  doc.setTextColor(...COL.slate);
  gap(4);

  // Safety notice box
  const safetyLines = doc.splitTextToSize(sanitizePdfText(L.safetyNotice), contentW - 8);
  const boxH = safetyLines.length * lineHeightMm(8.5) + 8;
  needSpace(boxH + 4);
  doc.setFillColor(...COL.safetyBg);
  doc.setDrawColor(...COL.safetyBorder);
  doc.setLineWidth(0.35);
  doc.roundedRect(margin, y, contentW, boxH, 2, 2, "FD");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...COL.slate);
  let sy = y + 5;
  for (const line of safetyLines) {
    doc.text(line, margin + 4, sy);
    sy += lineHeightMm(8.5);
  }
  y += boxH + 6;

  const patientLang = liveTranslationLanguageLabel(exportData.patientLanguage);
  const doctorLang = liveTranslationLanguageLabel(exportData.doctorLanguage);
  const practice = exportData.practice || {};

  drawSectionTitle(L.sectionPatient);
  drawMetaRow(L.patientName, exportData.patientName);
  drawMetaRow(L.birthDate, formatBirthDate(exportData.birthDate, uiLanguage));
  drawMetaRow(L.patientLanguage, patientLang);

  const practiceRows = [
    [L.doctorLanguage, doctorLang],
    [L.practiceName, practice.practiceName],
    [L.doctorName, practice.doctorName],
    [L.specialty, practice.specialty],
    [L.practiceAddress, practice.practiceAddress],
    [L.insurance, practice.insurance],
    [L.appointmentNote, practice.appointmentNote],
  ];
  const hasPractice = practiceRows.some(([, v]) => String(v || "").trim());
  if (hasPractice) {
    drawSectionTitle(L.sectionPractice);
    for (const [label, value] of practiceRows) {
      drawMetaRow(label, value);
    }
  } else {
    drawMetaRow(L.doctorLanguage, doctorLang);
  }

  drawSectionTitle(L.sectionSession);
  drawMetaRow(L.sessionStart, formatDateTime(exportData.sessionStartedAt, uiLanguage));
  drawMetaRow(L.sessionEnd, formatDateTime(exportData.sessionEndedAt, uiLanguage));
  drawMetaRow(L.languagePair, `${patientLang} ↔ ${doctorLang}`);
  drawMetaRow(
    L.autoSwitch,
    exportData.autoSwitchSpeaker ? L.yes : L.no,
  );

  drawSectionTitle(L.sectionConversation);

  const transcript = exportData.transcript || [];
  if (transcript.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(bodySize);
    doc.setTextColor(...COL.slateMuted);
    drawWrapped(L.notProvided, contentW, bodySize);
    doc.setTextColor(...COL.slate);
  }

  for (const turn of transcript) {
    const speaker = turn.speaker === "patient" ? L.speakerPatient : L.speakerDoctor;
    const srcLang = liveTranslationLanguageLabel(turn.sourceLanguage);
    const tgtLang = liveTranslationLanguageLabel(turn.targetLanguage);
    const timeStr = formatDateTime(turn.timestamp, uiLanguage);

    gap(6);
    needSpace(24);
    doc.setDrawColor(...COL.rule);
    doc.setLineWidth(0.2);
    doc.line(margin, y, pageWidth - margin, y);
    gap(5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...COL.teal);
    drawWrapped(speaker, contentW, 11);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...COL.slateMuted);
    drawWrapped(
      `${timeStr} · ${srcLang} → ${tgtLang} · ${statusLabel(L, turn.status)}`,
      contentW,
      8.5,
    );
    doc.setTextColor(...COL.slate);
    gap(3);

    if (turn.status === "corrected" && (turn.wrongOriginalText || turn.wrongTranslatedText)) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(labelSize);
      drawWrapped(L.wrongVersion, contentW, labelSize);
      gap(1);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(bodySize);
      if (turn.wrongOriginalText) {
        drawWrapped(`${L.originalLabel} (${srcLang}): ${turn.wrongOriginalText}`, contentW, bodySize);
        gap(2);
      }
      if (turn.wrongTranslatedText) {
        drawWrapped(`${L.translationLabel} (${tgtLang}): ${turn.wrongTranslatedText}`, contentW, bodySize);
        gap(3);
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(labelSize);
      drawWrapped(L.correctedVersion, contentW, labelSize);
      gap(2);
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(labelSize);
    drawWrapped(`${L.originalLabel} (${srcLang}):`, contentW, labelSize);
    gap(1);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(bodySize);
    if (turn.originalMissing || !String(turn.originalText || "").trim()) {
      doc.setFont("helvetica", "italic");
      drawWrapped(L.originalMissing, contentW, bodySize);
    } else {
      drawWrapped(turn.originalText, contentW, bodySize);
    }
    gap(3);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(labelSize);
    drawWrapped(`${L.translationLabel} (${tgtLang}):`, contentW, labelSize);
    gap(1);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(bodySize);
    drawWrapped(turn.translatedText || L.notProvided, contentW, bodySize);
    gap(2);
  }

  applyFooters(doc, L, pageWidth, pageHeight, margin, generatedAt);

  const datePart = (exportData.sessionEndedAt || "").slice(0, 10) || "export";
  const filename = L.filename.replace(".pdf", `-${datePart}.pdf`);

  return { doc, pdfFilename: filename };
}

/**
 * @param {ReturnType<typeof buildExportMetadata>} exportData
 * @param {string} uiLanguage
 */
export function downloadLiveTranslationPdf(exportData, uiLanguage) {
  const built = buildLiveTranslationPdfDocument(exportData, uiLanguage);
  if (!built) return false;
  built.doc.save(built.pdfFilename);
  return true;
}
