/** §9–§12 — English AGB */
export default [
  {
    id: "agb-9-nutzereingaben",
    heading: "§9 User input and AI outputs",
    blocks: [
      {
        type: "html",
        html: `
<p>(1) The user remains the holder of any rights in their inputs (e.g. texts, images), to the extent protectable under copyright.</p>
<p>(2) The user grants the provider a simple, worldwide licence to use their inputs to deliver the contractual services, to process them via AI services, and to use them in anonymised or aggregated form to improve and analyse the service.</p>
<p>(3) Outputs generated by AI serve exclusively for initial orientation. They may be incorrect, incomplete, or factually wrong and must not be understood as a medical diagnosis or binding recommendation.</p>
`.trim(),
      },
    ],
  },
  {
    id: "agb-10-haftung",
    heading: "§10 Liability",
    blocks: [
      {
        type: "html",
        html: `
<p>(1) The provider has unlimited liability for damage arising from injury to life, body, or health based on intentional or negligent breach of duty by the provider, its legal representatives, or vicarious agents, as well as under product liability law.</p>
<p>(2) For other damage the provider has unlimited liability in cases of intent and gross negligence.</p>
<p>(3) In cases of ordinary negligence the provider is liable only for breach of a material contractual obligation (cardinal duty). In that case liability is limited to damage typically foreseeable.</p>
<p>(4) Further liability of the provider is excluded. This also applies to indirect damage, lost profit, or loss of data where permitted by law.</p>
<p>(5) Using the App as a basis for medical diagnoses or therapies is at the user’s own risk and is not the purpose of the contract.</p>
`.trim(),
      },
    ],
  },
  {
    id: "agb-11-laufzeit",
    heading: "§11 Term, suspension and termination",
    blocks: [
      {
        type: "html",
        html: `
<p>(1) The user agreement is concluded for an indefinite period.</p>
<p>(2) The user may delete their account in the App at any time or stop using the service.</p>
<p>(3) The provider may suspend the user’s access in whole or in part or terminate the agreement for cause if the user materially breaches these Terms, abuses the App, or circumvents security mechanisms.</p>
<p>(4) Deleting the App account does <strong>not</strong> terminate a subscription concluded via the App Store or Play Store. Subscriptions must be cancelled separately in the respective store.</p>
`.trim(),
      },
    ],
  },
  {
    id: "agb-12-datenschutz",
    heading: "§12 Privacy",
    blocks: [
      {
        type: "html",
        html: `
<p>Information on the processing of personal data, in particular health data within the meaning of Art.&nbsp;9 GDPR, is set out in the <a href="/datenschutz">MedScoutX privacy policy</a>. Because of the sensitivity of the data, the App is intended exclusively for adult users (18+).</p>
`.trim(),
      },
    ],
  },
];
