/**
 * Client-side catalog of standard anamnesis questions.
 * Used in the editor "Insert standard question" dropdown.
 */
export const STANDARD_QUESTION_CATALOG = [
  // ── Aktuelles Anliegen ──────────────────────────────────────────────────────
  {
    id: "hauptbeschwerde",
    labelKey: "stdQ_hauptbeschwerde",
    type: "textarea",
    isRequired: true,
    responseMaxLength: 1000,
    labelJson: { de: "Was ist der Grund Ihres Besuchs?", en: "What is the reason for your visit?", fr: "Quelle est la raison de votre consultation ?", it: "Qual è il motivo della sua visita?", es: "¿Cuál es el motivo de su visita?" },
    hintJson:  { de: "Bitte so genau wie möglich beschreiben", en: "Please describe as precisely as possible", fr: "Décrivez aussi précisément que possible", it: "Descrivere il più precisamente possibile", es: "Describa lo más preciso posible" },
    optionsJson: null,
  },
  {
    id: "beschwerden_dauer",
    labelKey: "stdQ_beschwerden_dauer",
    type: "text",
    isRequired: true,
    responseMaxLength: 250,
    labelJson: { de: "Seit wann bestehen die Beschwerden?", en: "How long have you had these symptoms?", fr: "Depuis quand avez-vous ces symptômes ?", it: "Da quanto tempo ha questi sintomi?", es: "¿Desde cuándo tiene estos síntomas?" },
    hintJson:  { de: "z. B. seit 3 Tagen, seit 2 Wochen", en: "e.g. for 3 days, for 2 weeks", fr: "p. ex. depuis 3 jours, depuis 2 semaines", it: "es. da 3 giorni, da 2 settimane", es: "p. ej. desde hace 3 días" },
    optionsJson: null,
  },
  {
    id: "beschwerden_ort",
    labelKey: "stdQ_beschwerden_ort",
    type: "text",
    isRequired: false,
    responseMaxLength: 250,
    labelJson: { de: "Wo treten die Beschwerden auf?", en: "Where are the symptoms located?", fr: "Où se situent les symptômes ?", it: "Dove si manifestano i sintomi?", es: "¿Dónde se localizan los síntomas?" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "heute_wichtig",
    labelKey: "stdQ_heute_wichtig",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 500,
    labelJson: { de: "Was ist Ihnen heute besonders wichtig?", en: "What is most important to you today?", fr: "Qu'est-ce qui est le plus important pour vous aujourd'hui ?", it: "Cosa è più importante per lei oggi?", es: "¿Qué es más importante para usted hoy?" },
    hintJson:  null,
    optionsJson: null,
  },
  // ── Beschwerden und Verlauf ─────────────────────────────────────────────────
  {
    id: "beschwerden_veraenderung",
    labelKey: "stdQ_beschwerden_veraenderung",
    type: "single_choice",
    isRequired: false,
    labelJson: { de: "Haben sich die Beschwerden verändert?", en: "Have your symptoms changed?", fr: "Vos symptômes ont-ils évolué ?", it: "I suoi sintomi sono cambiati?", es: "¿Han cambiado sus síntomas?" },
    hintJson:  null,
    optionsJson: [
      { de: "Besser",      en: "Better",      fr: "Mieux",      it: "Meglio",    es: "Mejor"      },
      { de: "Schlechter",  en: "Worse",       fr: "Pire",       it: "Peggio",    es: "Peor"       },
      { de: "Unverändert", en: "Unchanged",   fr: "Inchangé",   it: "Invariato", es: "Sin cambios" },
      { de: "Wechselnd",   en: "Fluctuating", fr: "Variable",   it: "Variabile", es: "Variable"   },
    ],
  },
  {
    id: "begleitsymptome",
    labelKey: "stdQ_begleitsymptome",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 500,
    labelJson: { de: "Gibt es Begleitsymptome?", en: "Are there accompanying symptoms?", fr: "Y a-t-il des symptômes associés ?", it: "Ci sono sintomi associati?", es: "¿Hay síntomas acompañantes?" },
    hintJson:  { de: "z. B. Fieber, Übelkeit, Schwindel", en: "e.g. fever, nausea, dizziness", fr: "p. ex. fièvre, nausées, vertiges", it: "es. febbre, nausea, vertigini", es: "p. ej. fiebre, náuseas, mareos" },
    optionsJson: null,
  },
  {
    id: "schmerzstaerke",
    labelKey: "stdQ_schmerzstaerke",
    type: "number",
    isRequired: false,
    labelJson: { de: "Schmerzstärke (0 = kein Schmerz, 10 = unerträglicher Schmerz)", en: "Pain intensity (0 = no pain, 10 = unbearable)", fr: "Intensité de la douleur (0 = aucune, 10 = insupportable)", it: "Intensità del dolore (0 = nessun dolore, 10 = insopportabile)", es: "Intensidad del dolor (0 = sin dolor, 10 = insoportable)" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "schmerzcharakter",
    labelKey: "stdQ_schmerzcharakter",
    type: "single_choice",
    isRequired: false,
    labelJson: { de: "Schmerzcharakter", en: "Pain character", fr: "Caractère de la douleur", it: "Carattere del dolore", es: "Carácter del dolor" },
    hintJson:  null,
    optionsJson: [
      { de: "Stechend",    en: "Stabbing",  fr: "Lancinant",  it: "Pungente",    es: "Punzante"   },
      { de: "Dumpf",       en: "Dull",      fr: "Sourd",      it: "Sordo",       es: "Sordo"      },
      { de: "Brennend",    en: "Burning",   fr: "Brûlant",    it: "Bruciante",   es: "Ardiente"   },
      { de: "Drückend",    en: "Pressing",  fr: "Oppressif",  it: "Pressante",   es: "Opresivo"   },
      { de: "Krampfartig", en: "Cramping",  fr: "Crampes",    it: "Cramposo",    es: "Calambre"   },
    ],
  },
  {
    id: "beschwerden_einfluss",
    labelKey: "stdQ_beschwerden_einfluss",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 800,
    labelJson: { de: "Was verbessert oder verschlechtert die Beschwerden?", en: "What improves or worsens the symptoms?", fr: "Qu'est-ce qui améliore ou aggrave les symptômes ?", it: "Cosa migliora o peggiora i sintomi?", es: "¿Qué mejora o empeora los síntomas?" },
    hintJson:  null,
    optionsJson: null,
  },
  // ── Medikamente und Allergien ───────────────────────────────────────────────
  {
    id: "medikamente",
    labelKey: "stdQ_medikamente",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 1000,
    labelJson: { de: "Nehmen Sie aktuell Medikamente? (Name, Dosierung, Häufigkeit)", en: "Do you currently take any medications? (name, dosage, frequency)", fr: "Prenez-vous actuellement des médicaments ? (nom, dosage, fréquence)", it: "Assume attualmente farmaci? (nome, dosaggio, frequenza)", es: "¿Toma actualmente medicamentos? (nombre, dosis, frecuencia)" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "allergien",
    labelKey: "stdQ_allergien",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 500,
    labelJson: { de: "Sind Allergien oder Unverträglichkeiten bekannt?", en: "Are any allergies or intolerances known?", fr: "Des allergies ou intolérances sont-elles connues ?", it: "Sono note allergie o intolleranze?", es: "¿Se conocen alergias o intolerancias?" },
    hintJson:  { de: "z. B. Penicillin, Latex, Nüsse", en: "e.g. penicillin, latex, nuts", fr: "p. ex. pénicilline, latex", it: "es. penicillina, lattice", es: "p. ej. penicilina, látex" },
    optionsJson: null,
  },
  {
    id: "medikamente_geaendert",
    labelKey: "stdQ_medikamente_geaendert",
    type: "yes_no",
    isRequired: false,
    labelJson: { de: "Wurden Medikamente kürzlich verändert?", en: "Have any medications been recently changed?", fr: "Des médicaments ont-ils été récemment modifiés ?", it: "Sono stati modificati dei farmaci di recente?", es: "¿Se han modificado medicamentos recientemente?" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "blutverdünner",
    labelKey: "stdQ_blutverdünner",
    type: "yes_no",
    isRequired: false,
    labelJson: { de: "Nehmen Sie Blutverdünner / Gerinnungshemmer?", en: "Do you take blood thinners / anticoagulants?", fr: "Prenez-vous des anticoagulants ?", it: "Assume anticoagulanti?", es: "¿Toma anticoagulantes?" },
    hintJson:  null,
    optionsJson: null,
  },
  // ── Vorerkrankungen und Operationen ────────────────────────────────────────
  {
    id: "vorerkrankungen",
    labelKey: "stdQ_vorerkrankungen",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 1000,
    labelJson: { de: "Sind relevante Vorerkrankungen bekannt?", en: "Are there any relevant medical conditions?", fr: "Y a-t-il des antécédents médicaux pertinents ?", it: "Ci sono patologie rilevanti note?", es: "¿Existen enfermedades previas relevantes?" },
    hintJson:  { de: "z. B. Bluthochdruck, Diabetes, Herzerkrankung", en: "e.g. hypertension, diabetes, heart disease", fr: "p. ex. hypertension, diabète", it: "es. ipertensione, diabete", es: "p. ej. hipertensión, diabetes" },
    optionsJson: null,
  },
  {
    id: "operationen",
    labelKey: "stdQ_operationen",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 800,
    labelJson: { de: "Gab es frühere Operationen?", en: "Have you had any previous surgeries?", fr: "Avez-vous déjà subi des opérations ?", it: "Ha avuto interventi chirurgici precedenti?", es: "¿Ha tenido cirugías previas?" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "familienanamnese",
    labelKey: "stdQ_familienanamnese",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 800,
    labelJson: { de: "Gibt es relevante Erkrankungen in der Familie?", en: "Are there any relevant conditions in the family?", fr: "Y a-t-il des maladies familiales pertinentes ?", it: "Ci sono malattie rilevanti in famiglia?", es: "¿Hay enfermedades relevantes en la familia?" },
    hintJson:  { de: "z. B. Herzerkrankungen, Diabetes, Krebs", en: "e.g. heart disease, diabetes, cancer", fr: "p. ex. maladies cardiaques, diabète, cancer", it: "es. malattie cardiache, diabete, cancro", es: "p. ej. enfermedades cardíacas, diabetes, cáncer" },
    optionsJson: null,
  },
  // ── Lebenssituation und Risikofaktoren ──────────────────────────────────────
  {
    id: "rauchen",
    labelKey: "stdQ_rauchen",
    type: "single_choice",
    isRequired: false,
    labelJson: { de: "Rauchen Sie?", en: "Do you smoke?", fr: "Fumez-vous ?", it: "Fuma?", es: "¿Fuma usted?" },
    hintJson:  null,
    optionsJson: [
      { de: "Nein",   en: "No",         fr: "Non",          it: "No",         es: "No"            },
      { de: "Ja",     en: "Yes",        fr: "Oui",          it: "Sì",         es: "Sí"            },
      { de: "Früher", en: "Previously", fr: "Anciennement", it: "In passato", es: "Anteriormente" },
    ],
  },
  {
    id: "alkohol",
    labelKey: "stdQ_alkohol",
    type: "single_choice",
    isRequired: false,
    labelJson: { de: "Trinken Sie Alkohol?", en: "Do you drink alcohol?", fr: "Consommez-vous de l'alcool ?", it: "Consuma alcol?", es: "¿Consume alcohol?" },
    hintJson:  null,
    optionsJson: [
      { de: "Nein",         en: "No",                fr: "Non",                     it: "No",              es: "No"                  },
      { de: "Gelegentlich", en: "Occasionally",      fr: "Occasionnellement",        it: "Occasionalmente", es: "Ocasionalmente"      },
      { de: "Regelmäßig",  en: "Regularly",          fr: "Régulièrement",            it: "Regolarmente",    es: "Regularmente"        },
      { de: "Keine Angabe", en: "Prefer not to say", fr: "Ne souhaite pas répondre", it: "Non rispondo",    es: "Prefiero no decirlo" },
    ],
  },
  {
    id: "belastungen",
    labelKey: "stdQ_belastungen",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 500,
    labelJson: { de: "Gibt es berufliche oder private Belastungen, die relevant sein könnten?", en: "Are there occupational or personal stressors that might be relevant?", fr: "Y a-t-il des facteurs de stress professionnels ou personnels potentiellement pertinents ?", it: "Ci sono fattori di stress professionali o personali rilevanti?", es: "¿Hay factores estresantes laborales o personales que puedan ser relevantes?" },
    hintJson:  null,
    optionsJson: null,
  },
  // ── Schwangerschaft ─────────────────────────────────────────────────────────
  {
    id: "schwangerschaft",
    labelKey: "stdQ_schwangerschaft",
    type: "single_choice",
    isRequired: false,
    labelJson: { de: "Besteht eine Schwangerschaft oder könnte eine bestehen?", en: "Are you pregnant or could you be pregnant?", fr: "Êtes-vous enceinte ou pourriez-vous l'être ?", it: "È incinta o potrebbe esserlo?", es: "¿Está embarazada o podría estarlo?" },
    hintJson:  null,
    optionsJson: [
      { de: "Nein",                          en: "No",            fr: "Non",          it: "No",              es: "No"        },
      { de: "Ja",                            en: "Yes",           fr: "Oui",          it: "Sì",              es: "Sí"        },
      { de: "Unklar",                        en: "Unclear",       fr: "Incertain",    it: "Incerto",         es: "Incierto"  },
      { de: "Nicht relevant / keine Angabe", en: "Not applicable", fr: "Non applicable", it: "Non applicabile", es: "No aplica" },
    ],
  },
  {
    id: "stillzeit",
    labelKey: "stdQ_stillzeit",
    type: "single_choice",
    isRequired: false,
    labelJson: { de: "Stillen Sie aktuell?", en: "Are you currently breastfeeding?", fr: "Allaitez-vous actuellement ?", it: "Sta allattando al seno?", es: "¿Está amamantando actualmente?" },
    hintJson:  null,
    optionsJson: [
      { de: "Nein",                          en: "No",            fr: "Non",          it: "No",              es: "No"        },
      { de: "Ja",                            en: "Yes",           fr: "Oui",          it: "Sì",              es: "Sí"        },
      { de: "Nicht relevant / keine Angabe", en: "Not applicable", fr: "Non applicable", it: "Non applicabile", es: "No aplica" },
    ],
  },
  // ── Praxis ──────────────────────────────────────────────────────────────────
  {
    id: "fragen_praxis",
    labelKey: "stdQ_fragen_praxis",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 500,
    labelJson: { de: "Welche Fragen möchten Sie im Termin stellen?", en: "What questions would you like to ask during the appointment?", fr: "Quelles questions souhaitez-vous poser lors du rendez-vous ?", it: "Quali domande desidera porre durante la visita?", es: "¿Qué preguntas le gustaría hacer durante la cita?" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "dokumente",
    labelKey: "stdQ_dokumente",
    type: "yes_no",
    isRequired: false,
    labelJson: { de: "Bringen Sie Befunde oder Dokumente mit?", en: "Are you bringing any test results or documents?", fr: "Apportez-vous des résultats ou des documents ?", it: "Porta con sé referti o documenti?", es: "¿Trae consigo resultados o documentos?" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "hinweise_praxis",
    labelKey: "stdQ_hinweise_praxis",
    type: "textarea",
    isRequired: false,
    responseMaxLength: 500,
    labelJson: { de: "Wichtige Hinweise oder Anmerkungen für das Praxisteam", en: "Important notes for the practice team", fr: "Remarques importantes pour l'équipe", it: "Note importanti per il team dello studio", es: "Notas importantes para el equipo" },
    hintJson:  null,
    optionsJson: null,
  },
  {
    id: "dolmetscher",
    labelKey: "stdQ_dolmetscher",
    type: "yes_no",
    isRequired: false,
    labelJson: { de: "Benötigen Sie einen Dolmetscher?", en: "Do you need an interpreter?", fr: "Avez-vous besoin d'un interprète ?", it: "Ha bisogno di un interprete?", es: "¿Necesita un intérprete?" },
    hintJson:  null,
    optionsJson: null,
  },
];

export function emptyLangMap() {
  return { de: "", en: "", fr: "", it: "", es: "" };
}

export function newDraftQuestion() {
  return {
    _clientId: `_new_${Math.random().toString(36).slice(2)}`,
    type: "text",
    labelJson: emptyLangMap(),
    hintJson: emptyLangMap(),
    optionsJson: [],
    isRequired: false,
    responseMaxLength: null,
  };
}

export function questionFromCatalog(catalogItem) {
  return {
    _clientId: `_new_${Math.random().toString(36).slice(2)}`,
    type: catalogItem.type,
    labelJson: { ...emptyLangMap(), ...catalogItem.labelJson },
    hintJson: catalogItem.hintJson ? { ...emptyLangMap(), ...catalogItem.hintJson } : emptyLangMap(),
    optionsJson: Array.isArray(catalogItem.optionsJson) ? catalogItem.optionsJson.map((o) => ({ ...emptyLangMap(), ...o })) : [],
    isRequired: Boolean(catalogItem.isRequired),
    responseMaxLength: catalogItem.responseMaxLength ?? null,
  };
}
