/**
 * Deterministic pre-visit intake steps (frontend-only MVP).
 * Title/explanation: keyed by locale for the patient-facing intake flow.
 */

export const PRE_VISIT_SESSION_KEY = "medscoutx_previsit_session";

/** Keys aligned with the agreed payload shape for PDF/API later */
export const PRE_VISIT_QUESTION_STEPS = [
  {
    key: "appointmentReason",
    title: {
      de: "Aktueller Anlass des Termins",
      en: "Reason for this appointment",
      fr: "Motif actuel du rendez-vous",
      es: "Motivo actual de la cita",
      it: "Motivo attuale dell'appuntamento",
      tr: "Bu randevunun güncel nedeni",
      ru: "Текущая причина этого визита",
      uk: "Поточна причина цього візиту",
      pt: "Motivo atual da consulta",
      ar: "السبب الحالي للموعد",
      fa: "دلیل فعلی ویزیت",
      ckb: "ھۆکاری ئێستای چاوپێکەوتن",
      ku: "Sedema niha ya serdanê",
      el: "Τρέχων λόγος της επίσκεψης",
      ro: "Motivul actual al vizitei",
      pl: "Aktualny powód wizyty",
    },
    explanation: {
      de: "Worum geht es bei diesem Besuch? Kurz in eigenen Worten.",
      en: "What is this visit about? Briefly, in your own words.",
      fr: "De quoi s'agit-il pour cette consultation ? Décrivez-le brièvement avec vos propres mots.",
      es: "¿De qué trata esta consulta? Descríbalo brevemente con sus propias palabras.",
      it: "Di cosa si tratta in questa visita? Descrivilo brevemente con parole tue.",
      tr: "Bu muayene neyle ilgili? Kendi sözlerinizle kısaca anlatın.",
      ru: "С чем связан этот визит? Кратко опишите своими словами.",
      uk: "З чим пов’язаний цей візит? Коротко опишіть своїми словами.",
      pt: "Sobre o que é esta consulta? Responda brevemente com as suas próprias palavras.",
      ar: "عن ماذا يدور هذا الموعد؟ اشرح ذلك باختصار بكلماتك.",
      fa: "این ویزیت دربارهٔ چیست؟ کوتاه و با واژه‌های خودتان توضیح دهید.",
      ckb: "ئەم چاوپێکەوتنە لەسەر چییە؟ بە کورتی و بە وشەکانی خۆت ڕوونی بکەرەوە.",
      ku: "Ev serdan li ser çi ye? Bi kurtî û bi gotinên xwe şirove bike.",
      el: "Τι αφορά αυτή η επίσκεψη; Περιγράψτε το σύντομα με δικά σας λόγια.",
      ro: "Despre ce este această vizită? Descrieți pe scurt, în cuvintele dumneavoastră.",
      pl: "Czego dotyczy ta wizyta? Opisz to krótko własnymi słowami.",
    },
  },
  {
    key: "symptomsOwnWords",
    title: {
      de: "Symptome in Ihren eigenen Worten",
      en: "Symptoms in your own words",
      fr: "Symptômes avec vos propres mots",
      es: "Síntomas con sus propias palabras",
      it: "Sintomi con parole tue",
      tr: "Semptomlar kendi sözlerinizle",
      ru: "Симптомы своими словами",
      uk: "Симптоми своїми словами",
      pt: "Sintomas com as suas próprias palavras",
      ar: "الأعراض بكلماتك",
      fa: "علائم با واژه‌های خودتان",
      ckb: "ئاڵامەکان بە وشەکانی خۆت",
      ku: "Belîşan bi gotinên xwe",
      el: "Συμπτώματα με δικά σας λόγια",
      ro: "Simptome în cuvintele dumneavoastră",
      pl: "Objawy własnymi słowami",
    },
    explanation: {
      de: "Was nehmen Sie wahr (z. B. Schmerz, Druck, Einschränkung)?",
      en: "What do you notice (e.g. pain, pressure, limitation)?",
      fr: "Que ressentez-vous ou qu'observez-vous (par ex. douleur, pression, limitation) ?",
      es: "¿Qué nota o percibe (p. ej. dolor, presión, limitación)?",
      it: "Che cosa noti o percepisci (ad es. dolore, pressione, limitazione)?",
      tr: "Ne fark ediyor veya hissediyorsunuz (ör. ağrı, baskı, kısıtlılık)?",
      ru: "Что вы замечаете или ощущаете (например, боль, давление, ограничение)?",
      uk: "Що ви помічаєте або відчуваєте (наприклад, біль, тиск, обмеження)?",
      pt: "O que nota ou sente (por ex. dor, pressão, limitação)?",
      ar: "ماذا تلاحظ أو تشعر (مثل ألم أو ضغط أو محدودية)؟",
      fa: "چه چیزی را متوجه می‌شوید یا احساس می‌کنید (مثلاً درد، فشار، محدودیت)؟",
      ckb: "چی تێدەگەیت یان ھەستی پێدەکەیت (بۆ نموونە ئازار، فشار، سنوورداری)؟",
      ku: "Tu çi têdigehî an hîs dikî (mînak ağrî, zext, astengî)?",
      el: "Τι παρατηρείτε ή αισθάνεστε (π.χ. πόνο, πίεση, περιορισμό);",
      ro: "Ce observați sau simțiți (de ex. durere, presiune, limitare)?",
      pl: "Co zauważasz lub odczuwasz (np. ból, ucisk, ograniczenie)?",
    },
  },
  {
    key: "onsetAndCourse",
    title: {
      de: "Beginn und Verlauf",
      en: "Onset and course over time",
      fr: "Début et évolution",
      es: "Inicio y evolución",
      it: "Inizio e decorso",
      tr: "Başlangıç ve zaman içindeki seyir",
      ru: "Начало и развитие во времени",
      uk: "Початок і розвиток у часі",
      pt: "Início e evolução",
      ar: "البداية والتطور",
      fa: "شروع و روند",
      ckb: "دەستپێکردن و ڕێڕەو",
      ku: "Destpêk û pêşketin",
      el: "Έναρξη και εξέλιξη",
      ro: "Debut și evoluție",
      pl: "Początek i przebieg",
    },
    explanation: {
      de: "Seit wann bestehen die Beschwerden? Wie haben sie sich entwickelt?",
      en: "When did symptoms start? How have they changed since then?",
      fr: "Depuis quand les symptômes existent-ils ? Comment ont-ils évolué depuis ?",
      es: "¿Desde cuándo existen los síntomas? ¿Cómo han cambiado desde entonces?",
      it: "Da quando sono presenti i sintomi? Come sono cambiati nel tempo?",
      tr: "Semptomlar ne zamandan beri var? O zamandan beri nasıl değişti?",
      ru: "С какого времени есть симптомы? Как они изменялись с тех пор?",
      uk: "Відколи є симптоми? Як вони змінювалися відтоді?",
      pt: "Desde quando existem os sintomas? Como mudaram desde então?",
      ar: "منذ متى توجد الأعراض؟ وكيف تغيّرت منذ ذلك الحين؟",
      fa: "علائم از چه زمانی شروع شده‌اند؟ از آن زمان چگونه تغییر کرده‌اند؟",
      ckb: "ئاڵامەکان لە کێوە دەست پێکردووە؟ لەو کاتەوە چۆن گۆڕاون؟",
      ku: "Belîşan ji kengê dest pê kirin? Ji wê demê ve çawa guhertine?",
      el: "Από πότε υπάρχουν τα συμπτώματα; Πώς έχουν αλλάξει από τότε;",
      ro: "De când au început simptomele? Cum s-au schimbat de atunci?",
      pl: "Od kiedy występują objawy? Jak zmieniły się od tego czasu?",
    },
  },
  {
    key: "medications",
    title: {
      de: "Aktuelle Medikamente",
      en: "Current medications",
      fr: "Médicaments actuels",
      es: "Medicamentos actuales",
      it: "Farmaci attuali",
      tr: "Güncel ilaçlar",
      ru: "Текущие лекарства",
      uk: "Поточні ліки",
      pt: "Medicação atual",
      ar: "الأدوية الحالية",
      fa: "داروهای فعلی",
      ckb: "دەرمانە ئێستاکان",
      ku: "Dermanên niha",
      el: "Τρέχοντα φάρμακα",
      ro: "Medicamente actuale",
      pl: "Aktualne leki",
    },
    explanation: {
      de: "Welche Medikamente nehmen Sie ein (Name, Dosis, wie oft)?",
      en: "Which medicines do you take (name, dose, how often)?",
      fr: "Quels médicaments prenez-vous (nom, dose, fréquence) ?",
      es: "¿Qué medicamentos toma (nombre, dosis, frecuencia)?",
      it: "Quali farmaci assumi (nome, dose, frequenza)?",
      tr: "Hangi ilaçları kullanıyorsunuz (ad, doz, sıklık)?",
      ru: "Какие лекарства вы принимаете (название, дозировка, как часто)?",
      uk: "Які ліки ви приймаєте (назва, дозування, як часто)?",
      pt: "Que medicamentos toma (nome, dose, com que frequência)?",
      ar: "ما الأدوية التي تتناولها (الاسم، الجرعة، عدد المرات)؟",
      fa: "چه داروهایی مصرف می‌کنید (نام، دوز، چند بار)؟",
      ckb: "چی دەرمانێک بەکاردەھێنیت (ناو، دۆز، چەندجار)؟",
      ku: "Tu kîjan dermanan dixwî (nav, doz, çend caran)?",
      el: "Ποια φάρμακα λαμβάνετε (όνομα, δόση, πόσο συχνά);",
      ro: "Ce medicamente luați (nume, doză, cât de des)?",
      pl: "Jakie leki przyjmujesz (nazwa, dawka, jak często)?",
    },
  },
  {
    key: "preExistingConditions",
    title: {
      de: "Bekannte Vorerkrankungen",
      en: "Known pre-existing conditions",
      fr: "Antécédents connus",
      es: "Enfermedades previas conocidas",
      it: "Patologie pregresse note",
      tr: "Bilinen hastalık geçmişi",
      ru: "Известные хронические заболевания",
      uk: "Відомі хронічні захворювання",
      pt: "Doenças pré-existentes conhecidas",
      ar: "الأمراض المزمنة المعروفة",
      fa: "بیماری‌های زمینه‌ای شناخته‌شده",
      ckb: "نەخۆشییە درێژخایەنە ناسراوەکان",
      ku: "Nexweşiyên berê yên naskirî",
      el: "Γνωστές προϋπάρχουσες παθήσεις",
      ro: "Afecțiuni preexistente cunoscute",
      pl: "Znane choroby przewlekłe",
    },
    explanation: {
      de: "Welche Diagnosen oder chronischen Erkrankungen sind bekannt?",
      en: "Which diagnoses or chronic conditions are known?",
      fr: "Quels diagnostics ou problèmes chroniques sont déjà connus ?",
      es: "¿Qué diagnósticos o enfermedades crónicas son conocidos?",
      it: "Quali diagnosi o condizioni croniche sono note?",
      tr: "Hangi tanılar veya kronik hastalıklar biliniyor?",
      ru: "Какие диагнозы или хронические заболевания вам известны?",
      uk: "Які діагнози або хронічні захворювання вам відомі?",
      pt: "Que diagnósticos ou doenças crónicas são conhecidos?",
      ar: "ما التشخيصات أو الأمراض المزمنة المعروفة لديك؟",
      fa: "چه تشخیص‌ها یا بیماری‌های مزمنی برایتان شناخته‌شده است؟",
      ckb: "کام دەستنیشانکردن یان نەخۆشییە درێژخایەنەکانت پێ ناسراون؟",
      ku: "Tu kîjan teşhîs an nexweşiyên dirêjdem hene ku tên zanîn?",
      el: "Ποιες διαγνώσεις ή χρόνιες παθήσεις είναι γνωστές;",
      ro: "Ce diagnostice sau afecțiuni cronice sunt cunoscute?",
      pl: "Jakie rozpoznania lub choroby przewlekłe są znane?",
    },
  },
  {
    key: "relevantDocuments",
    title: {
      de: "Relevante Unterlagen",
      en: "Relevant documents",
      fr: "Documents pertinents",
      es: "Documentos relevantes",
      it: "Documenti rilevanti",
      tr: "İlgili belgeler",
      ru: "Важные документы",
      uk: "Важливі документи",
      pt: "Documentos relevantes",
      ar: "المستندات ذات الصلة",
      fa: "مدارک مرتبط",
      ckb: "بەڵگەنامە پەیوەندیدارەکان",
      ku: "Belgeyên girêdayî",
      el: "Σχετικά έγγραφα",
      ro: "Documente relevante",
      pl: "Istotne dokumenty",
    },
    explanation: {
      de: "Welche Befunde oder Unterlagen möchten Sie erwähnen (z. B. Labor, Vor-Befunde)?",
      en: "Which results or documents should be mentioned (e.g. labs, prior reports)?",
      fr: "Quels résultats ou documents souhaitez-vous mentionner (par ex. analyses, comptes rendus antérieurs) ?",
      es: "¿Qué resultados o documentos quiere mencionar (p. ej. análisis, informes previos)?",
      it: "Quali referti o documenti vuoi indicare (ad es. esami di laboratorio o referti precedenti)?",
      tr: "Hangi sonuçları veya belgeleri belirtmek istersiniz (ör. laboratuvar, önceki raporlar)?",
      ru: "Какие результаты или документы вы хотите указать (например, анализы, предыдущие заключения)?",
      uk: "Які результати або документи ви хочете зазначити (наприклад, аналізи, попередні висновки)?",
      pt: "Que resultados ou documentos gostaria de mencionar (por ex. análises, relatórios anteriores)?",
      ar: "ما النتائج أو المستندات التي تريد ذكرها (مثل التحاليل أو التقارير السابقة)؟",
      fa: "چه نتیجه‌ها یا مدارکی را می‌خواهید ذکر کنید (مثلاً آزمایش‌ها یا گزارش‌های قبلی)؟",
      ckb: "کام ئەنجام یان بەڵگەنامانە دەتەوێت ئاماژەیان پێ بدەیت (بۆ نموونە تاقیکردنەوە یان ڕاپۆرتی پێشوو)؟",
      ku: "Tu dixwazî kîjan encam an belgeyan bibêjî (mînak test, raporên berê)?",
      el: "Ποια αποτελέσματα ή έγγραφα θέλετε να αναφέρετε (π.χ. εξετάσεις, παλαιότερες γνωματεύσεις);",
      ro: "Ce rezultate sau documente doriți să menționați (de ex. analize, rapoarte anterioare)?",
      pl: "Jakie wyniki lub dokumenty chcesz wskazać (np. badania, wcześniejsze opisy)?",
    },
  },
  {
    key: "patientQuestions",
    title: {
      de: "Fragen an die Ärztin / den Arzt",
      en: "Questions you want to ask",
      fr: "Questions que vous souhaitez poser",
      es: "Preguntas que quiere hacer",
      it: "Domande che vuoi porre",
      tr: "Sormak istediğiniz sorular",
      ru: "Вопросы, которые вы хотите задать",
      uk: "Запитання, які ви хочете поставити",
      pt: "Perguntas que quer fazer",
      ar: "الأسئلة التي تريد طرحها",
      fa: "پرسش‌هایی که می‌خواهید بپرسید",
      ckb: "ئەو پرسیارانەی دەتەوێت بیپرسی",
      ku: "Pirsên ku tu dixwazî bipirsî",
      el: "Ερωτήσεις που θέλετε να κάνετε",
      ro: "Întrebări pe care doriți să le puneți",
      pl: "Pytania, które chcesz zadać",
    },
    explanation: {
      de: "Was möchten Sie im Gespräch unbedingt klären?",
      en: "What do you want to clarify during the consultation?",
      fr: "Que souhaitez-vous absolument clarifier pendant la consultation ?",
      es: "¿Qué quiere aclarar sí o sí durante la consulta?",
      it: "Che cosa vuoi chiarire assolutamente durante la visita?",
      tr: "Görüşmede özellikle neyi netleştirmek istiyorsunuz?",
      ru: "Что вы обязательно хотите уточнить во время консультации?",
      uk: "Що ви обов’язково хочете уточнити під час консультації?",
      pt: "O que quer esclarecer obrigatoriamente durante a consulta?",
      ar: "ما الذي تريد توضيحه بالتأكيد أثناء الاستشارة؟",
      fa: "در گفت‌وگو حتماً چه چیزی را می‌خواهید روشن کنید؟",
      ckb: "لە گفتوگۆدا بە دڵنیاییەوە دەتەوێت چی ڕوون بکەیتەوە؟",
      ku: "Di hevdîtinê de tu bi mutleq çi dixwazî zelal bikî?",
      el: "Τι θέλετε οπωσδήποτε να ξεκαθαρίσετε κατά τη συνάντηση;",
      ro: "Ce doriți neapărat să clarificați în cadrul consultației?",
      pl: "Co chcesz koniecznie wyjaśnić podczas wizyty?",
    },
  },
];

export function createEmptyAnswers() {
  return {
    appointmentReason: "",
    symptomsOwnWords: "",
    onsetAndCourse: "",
    medications: "",
    preExistingConditions: "",
    relevantDocuments: "",
    patientQuestions: "",
  };
}

/** Pick localized string; fallback exact → en → de → first available */
export function pickLocalized(record, lang) {
  if (!record || typeof record !== "object") return "";
  const code = String(lang || "").split("-")[0].toLowerCase();
  if (record[code]) return record[code];
  if (code !== "de" && record.en) return record.en;
  if (record.de) return record.de;
  if (record.en) return record.en;
  const first = Object.values(record).find(Boolean);
  return first ?? "";
}
