/** Demo data when GOOGLE_PLACES_API_KEY is not configured (development only). */

export function buildDemoResults(center, specialty, language) {
  const isDe = language === "de";
  return [
    {
      placeId: "demo-1",
      name: isDe ? "Praxis am Stadtpark" : "City Park Medical Office",
      specialty,
      address: isDe ? "Musterstraße 12, 10115 Berlin" : "Sample Street 12, 10115 Berlin",
      latitude: center.lat + 0.008,
      longitude: center.lng + 0.006,
      distanceKm: 1.2,
      rating: 4.6,
      reviewCount: 312,
      websiteUrl: "https://example.com",
      mapsUrl: "https://www.google.com/maps",
      routeUrl: `https://www.google.com/maps/dir/?api=1&destination=${center.lat},${center.lng}`,
      phone: "+49 30 1234567",
      openingHoursSummary: isDe ? "Mo–Fr 8:00–18:00" : "Mon–Fri 8:00–18:00",
      languages: isDe ? ["Deutsch", "English"] : ["German", "English"],
      bookingUrl: null,
    },
    {
      placeId: "demo-2",
      name: isDe ? "Gemeinschaftspraxis Nord" : "North Community Practice",
      specialty,
      address: isDe ? "Nordweg 4, 10115 Berlin" : "North Way 4, 10115 Berlin",
      latitude: center.lat - 0.012,
      longitude: center.lng + 0.01,
      distanceKm: 2.8,
      rating: 4.4,
      reviewCount: 89,
      websiteUrl: null,
      mapsUrl: "https://www.google.com/maps",
      routeUrl: `https://www.google.com/maps/dir/?api=1&destination=${center.lat},${center.lng}`,
      phone: null,
      openingHoursSummary: null,
      languages: [],
      bookingUrl: null,
    },
    {
      placeId: "demo-3",
      name: isDe ? "Medizinisches Zentrum Süd" : "South Medical Center",
      specialty,
      address: isDe ? "Südallee 88" : "South Avenue 88",
      latitude: center.lat + 0.02,
      longitude: center.lng - 0.015,
      distanceKm: 4.5,
      rating: 5,
      reviewCount: 2,
      websiteUrl: "https://example.org",
      mapsUrl: "https://www.google.com/maps",
      routeUrl: `https://www.google.com/maps/dir/?api=1&destination=${center.lat},${center.lng}`,
      phone: "+49 30 7654321",
      openingHoursSummary: null,
      languages: [],
      bookingUrl: null,
    },
  ];
}
